nginx:
    image: atyenoria/openresty-proxy
    container_name: nginx
    ports:
        - "80:80"
    tty: true
    working_dir: /opt/openresty/nginx/test
    # command: sh boot.sh
    command: bash
    links:
       - "s1:s1"
       - "s2:s2"
    volumes:
    - ./config:/opt/openresty/nginx/test

s1:
    image: nginx
    container_name: s1
    ports:
        - "80"

s2:
    image: nginx
    container_name: s2
    ports:
        - "80"
