# nginx:
#     image: atyenoria/openresty-proxy
#     container_name: nginx
#     ports:
#         - "3306:3306"
#     tty: true
#     working_dir: /opt/openresty/nginx/test
#     command: bash
#     links:
#        - "s1:s1"
#        - "s2:s2"
#     volumes:
#     - ./config:/opt/openresty/nginx/test

nginx:
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  ports:
    - "80:80"



s1:
  container_name: s1
  image: wordpress
  links:
    - db1:mysql
  environment:
    - VIRTUAL_HOST=l1.com
  ports:
    - "9090:80"
db1:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: example




s2:
  container_name: s2
  image: wordpress
  links:
    - db2:mysql
  environment:
    - VIRTUAL_HOST=l.com
  ports:
    - "8080:80"
db2:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: example


