nginx:
    build: ../
    container_name: nginx
    ports:
        - "80:80"
    tty: true
    command: ls -la
    working_dir: /opt/openresty/nginx/test
    volumes:
    - ./config:/opt/openresty/nginx/test
