nginx:
    image: atyenoria/openresty-proxy
    container_name: nginx
    ports:
        - "3306:3306"
    tty: true
    working_dir: /opt/openresty/nginx/test
    command: sh boot.sh
    links:
       - "s1:s1"
       - "s2:s2"
    volumes:
    - ./config:/opt/openresty/nginx/test

s1:
  image: mariadb
  container_name: s1
  ports:
    - "3306"
  volumes:
    - "/var/lib/mysql"
  environment:
    MYSQL_ROOT_PASSWORD: "root"
    MYSQL_DATABASE: "root"


s2:
  image: mariadb
  container_name: s2
  ports:
    - "3306"
  volumes:
    - "/var/lib/mysql"
  environment:
    MYSQL_ROOT_PASSWORD: "root"
    MYSQL_DATABASE: "root"
